### PR TITLE
Fix ultimate-guitar url source

### PR DESCRIPTION
**Pull request by mugbug**
The https://tabs.ultimate-guitar.com source changed its website and now they generate its HTML from JS rendering. So the previous approach wasn't working. The change now uses Selenium to get the HTML source through chromedriver.
It's processing time to open the chords still has to be improved, once the window freezes during that. And which by the way may be fixed with multithreading.

### CODE REVIEW

**Comment by mugbug** [comment]
Actually, I'm not pretty sure about this PR, it's taking really long to open the chords. But I do really prefer the ultimate-guitar chords.

**Comment by fr31** [comment]
I've never used selenium and don't know much about it; but could qtwebdriver be used instead of chromedriver to avoid an additional dependency? Also I believe the chromedriver you included is the 64-bit linux version, so would this only work on 64-bit linux?

**Comment by MiniDigger** [comment]
This sounds really inefficient. If they render the data via js, the need to get the data via js from some Backend Service. Wouldn't it be easier to get the data using that Webservice?

**Comment by mugbug** [comment]
@fr31 I'm not sure if qtwebdriver could be used instead of chomedriver, but I believe you are right, it would only work on 64-bit Linux. Definitely not the best solution.
@MiniDigger about that, for sure there is a webservice that could be used to get the data instead of rendering the js, but I couldn't find an endpoint or something (actually, I don't really know the best way to look for that), so that was the solution I could find.
Anyway, I'm closing this PR and I'm going to search for a more efficient and cross-platform way to get this data.

**Pull request closed without merging**
